# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MIAS.ui'
#
# Created: Fri Apr  3 15:46:17 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(518, 540)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.grpSheets = QtGui.QGroupBox(Dialog)
        self.grpSheets.setEnabled(False)
        self.grpSheets.setGeometry(QtCore.QRect(40, 130, 201, 361))
        self.grpSheets.setObjectName(_fromUtf8("grpSheets"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.grpSheets)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 50, 481, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 471, 29))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.filename = QtGui.QLineEdit(self.layoutWidget)
        self.filename.setReadOnly(True)
        self.filename.setObjectName(_fromUtf8("filename"))
        self.horizontalLayout.addWidget(self.filename)
        self.btnOpen = QtGui.QPushButton(self.layoutWidget)
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.horizontalLayout.addWidget(self.btnOpen)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(230, 140, 266, 351))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radItemSingle = QtGui.QRadioButton(self.groupBox_2)
        self.radItemSingle.setObjectName(_fromUtf8("radItemSingle"))
        self.gridLayout.addWidget(self.radItemSingle, 2, 0, 1, 1)
        self.radItemRange = QtGui.QRadioButton(self.groupBox_2)
        self.radItemRange.setObjectName(_fromUtf8("radItemRange"))
        self.gridLayout.addWidget(self.radItemRange, 3, 0, 1, 1)
        self.spinItemSingle = QtGui.QSpinBox(self.groupBox_2)
        self.spinItemSingle.setProperty("value", 1)
        self.spinItemSingle.setObjectName(_fromUtf8("spinItemSingle"))
        self.gridLayout.addWidget(self.spinItemSingle, 2, 1, 1, 1)
        self.editItemRange = QtGui.QLineEdit(self.groupBox_2)
        self.editItemRange.setObjectName(_fromUtf8("editItemRange"))
        self.gridLayout.addWidget(self.editItemRange, 3, 1, 1, 1)
        self.radItemAll = QtGui.QRadioButton(self.groupBox_2)
        self.radItemAll.setChecked(True)
        self.radItemAll.setObjectName(_fromUtf8("radItemAll"))
        self.gridLayout.addWidget(self.radItemAll, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radColAll = QtGui.QRadioButton(self.groupBox_3)
        self.radColAll.setChecked(False)
        self.radColAll.setObjectName(_fromUtf8("radColAll"))
        self.verticalLayout_2.addWidget(self.radColAll)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radColRange = QtGui.QRadioButton(self.groupBox_3)
        self.radColRange.setChecked(True)
        self.radColRange.setObjectName(_fromUtf8("radColRange"))
        self.horizontalLayout_2.addWidget(self.radColRange)
        self.spinColFrom = QtGui.QSpinBox(self.groupBox_3)
        self.spinColFrom.setProperty("value", 3)
        self.spinColFrom.setObjectName(_fromUtf8("spinColFrom"))
        self.horizontalLayout_2.addWidget(self.spinColFrom)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spinColTo = QtGui.QSpinBox(self.groupBox_3)
        self.spinColTo.setProperty("value", 23)
        self.spinColTo.setObjectName(_fromUtf8("spinColTo"))
        self.horizontalLayout_2.addWidget(self.spinColTo)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.btnFullReport = QtGui.QPushButton(self.layoutWidget1)
        self.btnFullReport.setObjectName(_fromUtf8("btnFullReport"))
        self.verticalLayout.addWidget(self.btnFullReport)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnQuit = QtGui.QPushButton(self.layoutWidget1)
        self.btnQuit.setObjectName(_fromUtf8("btnQuit"))
        self.verticalLayout.addWidget(self.btnQuit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "MIAS v 0.1", None))
        self.label_2.setText(_translate("Dialog", "Meral\'s Item Analysis Software", None))
        self.grpSheets.setTitle(_translate("Dialog", "Select Sheet(s)", None))
        self.label.setText(_translate("Dialog", "File name", None))
        self.btnOpen.setText(_translate("Dialog", "Browse...", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Select Item(s)", None))
        self.radItemSingle.setToolTip(_translate("Dialog", "<html><head/><body><p>Display the analysis of the specified item only.</p></body></html>", None))
        self.radItemSingle.setText(_translate("Dialog", "Single item", None))
        self.radItemRange.setToolTip(_translate("Dialog", "<html><head/><body><p>Specify a comma-separated list and/or range for he items to analyze.</p><p>Example: 1, 3, 7-10 analyzes items 1,3,7,8,9,10.</p></body></html>", None))
        self.radItemRange.setText(_translate("Dialog", "Range", None))
        self.radItemAll.setToolTip(_translate("Dialog", "<html><head/><body><p>Generate report using all items in the selected exam(s).</p></body></html>", None))
        self.radItemAll.setText(_translate("Dialog", "All", None))
        self.label_3.setText(_translate("Dialog", "(e.g., 1, 3, 7-10)", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Columns of responses", None))
        self.radColAll.setToolTip(_translate("Dialog", "<html><head/><body><p>Choose this if the data contains exam responses only (and not student names, total grade of student, etc.)</p></body></html>", None))
        self.radColAll.setText(_translate("Dialog", "All columns", None))
        self.radColRange.setToolTip(_translate("Dialog", "<html><head/><body><p>If the file has extra columns in addition to exam responses, specify the response columns here.</p></body></html>", None))
        self.radColRange.setText(_translate("Dialog", "from", None))
        self.label_4.setText(_translate("Dialog", "to", None))
        self.btnFullReport.setToolTip(_translate("Dialog", "<html><head/><body><p>Display the detailed analysis of each item in selected exam(s).</p></body></html>", None))
        self.btnFullReport.setText(_translate("Dialog", "Generate Report", None))
        self.btnQuit.setText(_translate("Dialog", "Quit", None))

